authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'
urlpatterns = [
    path('register/', views.registerUser, name='register_user'),
    path('login/', views.loginUser, name='login_user'),
    path('logout/', views.logoutUser, name='logout_user'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.createTodo, name='create_todo'),
    path('current/', views.currentTodo, name='current_todo'),
    path('completed/', views.completedTodo, name='completed_todo'),
    path('todo/<int:todo_pk>/', views.viewTodo, name='view_todo'),
    path('completed/<int:todo_pk>/',
         views.taskAccomplished, name='task_accomplished'),
    path('delete/<int:todo_pk>/', views.deleteTodo, name='delete_todo'),
]

todo_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Auth
    path('auth/', include('authentication.urls')),

    # Application
    path('', include('todo.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, blank=False)
    memo = models.TextField(blank=True)
    important = models.BooleanField(default=False)
    datecompleted = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Todo"
        verbose_name_plural = "Todos"

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'memo', 'important']

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Title'
            }),
            'memo': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Memo...'
            }),
        }

authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def registerUser(request):
    if request.user.is_authenticated:
        return redirect('todo:index')

    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'User account was created!')

            login(request, user)

            return redirect('todo:current_todo')
        else:
            messages.warning(
                request, "An error has occured during registration")

    context = dict()
    context['form'] = form

    return render(request, 'authentication/register_user.html', context)


@csrf_exempt
def loginUser(request):
    if request.user.is_authenticated:
        return redirect('todo:index')

    form = AuthenticationForm()

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.warning(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return redirect('todo:index')
        else:
            messages.error(request, 'Username and password is incorrect')

    context = dict()
    context['form'] = form

    return render(request, 'authentication/login_user.html', context)


@csrf_exempt
def logoutUser(request):
    logout(request)
    messages.success(request, 'User was logged out')

    return redirect('todo:index')

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.utils import timezone

from .models import Todo
from .forms import TodoForm


def index(request):
    if request.user.is_authenticated:
        return redirect('todo:current_todo')

    return render(request, 'todo/index.html')


@csrf_exempt
def createTodo(request):
    form = TodoForm()

    if request.method == 'POST':
        form = TodoForm(request.POST)

        if form.is_valid():
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()

            return redirect('todo:current_todo')
        else:
            messages.warning(request, 'Bad data passed in. Try again!')

    context = dict()
    context['form'] = form

    return render(request, 'todo/create_todo.html', context)


def currentTodo(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=True)
    context = dict()
    context['todos'] = todos

    return render(request, 'todo/current_todo.html', context)


def completedTodo(request):
    todos = Todo.objects.filter(user=request.user, datecompleted__isnull=False)
    context = dict()
    context['todos'] = todos

    return render(request, 'todo/completed_todo.html', context)


@csrf_exempt
def viewTodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)
    form = TodoForm(instance=todo)

    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)

        if form.is_valid():
            form.save()

            return redirect('todo:current_todo')
        else:
            messages.warning(request, 'Bad data passed in. Try again!')

    context = dict()
    context['form'] = form
    context['todo'] = todo

    return render(request, 'todo/view_todo.html', context)


@csrf_exempt
def taskAccomplished(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)

    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()

        return redirect('todo:current_todo')


@csrf_exempt
def deleteTodo(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk, user=request.user)

    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.delete()

        return redirect('todo:current_todo')

authentication/templates/authentication/login_user.html
{% extends 'base.html' %}

{% block content %}

<br>

<div class="row justify-content-center">
    <div class="col-md-5">
        <h2>Log In</h2>
    </div>
</div>

<br>

<div class="row justify-content-center">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}

        <form method="POST">
            <div class="form-group">
                <label for="inputEmail">Username</label>
                <input type="text" name="username" class="form-control" id="inputEmail" placeholder="Username">
            </div>
            <p></p>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password" placeholder="Password">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Log In</button>
        </form>

        <hr>

        <div class="text-center">
            Need an account? <a href="{% url 'authentication:register_user' %}">SignUp</a> here
        </div>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/register_user.html
{% extends 'base.html' %}

{% block content %}

<br>

<div class="row justify-content-center">
    <div class="col-md-5">
        <h2>Sign Up</h2>
    </div>
</div>

<br>

<div class="row justify-content-center">
    <div class="col-md-5">
        <form method="POST">
            <div class="form-group">
                <label for="inputEmail">Username</label>
                <input type="text" name="username" class="form-control" id="inputEmail" placeholder="Username">
                <small id="usernameHelp" class="form-text text-muted">
                    Your username must be unique. We'll let you know if someone has taken it already.
                </small>
            </div>
            <p></p>
            <div class="form-group">
                <label for="inputPassword">Password</label>
                <input type="password" name="password1" class="form-control" id="inputPassword" placeholder="Password">
            </div>
            <p></p>
            <div class="form-group">
                <label for="inputPasswordConfirmation">Password Confirmation</label>
                <input type="password" name="password2" class="form-control" id="inputPasswordConfirmation"
                    placeholder="Password Confirmation">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Sign in</button>
        </form>

        <hr>

        <div class="text-center">
            Do you already have an account? <a href="{% url 'authentication:login_user' %}">Login</a> here
        </div>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flicker</title>

    <!-- CSS File -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- BootStrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- CSS Style - Redressed -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Redressed&display=swap" rel="stylesheet">
</head>

<body>
    <!-- Image and text -->
    <nav class="navbar" style="background-color: #e3f2fd;">
        <div class="container">
            <a class="navbar-brand" href="{% url 'todo:index' %}">
                <img src="https://i.pinimg.com/736x/e8/ac/ba/e8acba8e8c22739ddf316d8d8d8db791.jpg" alt="" width="30"
                    height="24" class="d-inline-block align-top">
                <span id="head">
                    Flicker
                </span>
            </a>

            {% if request.user.is_authenticated %}

            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:create_todo' %}">Create </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:current_todo' %}">Current</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:completed_todo' %}">Completed</a>
                </li>
            </ul>

            <form action="{% url 'authentication:logout_user' %}" method="POST">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <button type="submit" class="btn btn-secondary">Logout</button>
                    </li>
                </ul>
            </form>

            {% else %}

            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:register_user' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:login_user' %}">Login</a>
                </li>
            </ul>

            {% endif %}

        </div>
    </nav>

    <br>

    {% if messages %}
    {% for message in messages %}
    <div class="container">
        <center>
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        </center>
    </div>
    {% endfor %}
    {% endif %}

    <div class="container">
        {% block content %} {% endblock content %}
    </div>


    <!-- BootStrap Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>

</html>

todo/templates/todo/completed_todo.html
{% extends 'base.html' %}

{% block content %}

<h1>Completed Todos</h1>

<hr>

{% for todo in todos %}
<div class="card">
    <div class="card-body">
        <a href="{% url 'todo:view_todo' todo.id %}">
            {% if todo.important %}<strong>{% endif %}{{ todo.title }}{% if todo.important %}</strong>{% endif %}
        </a>
        {% if todo.memo %}<br>{{ todo.memo }}{% endif %}
        <br>
        {{ todo.datecompleted|date:'M j Y H:i' }}
    </div>
</div>

<br>

{% endfor %}

{% endblock content %}

todo/templates/todo/create_todo.html
{% extends 'base.html' %}

{% block content %}

<h1>Create</h1>

<hr>

<form method="POST">
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary">Create</button>
</form>

{% endblock content %}

todo/templates/todo/current_todo.html
{% extends 'base.html' %}

{% block content %}

<h1>Current Todos</h1>

<hr>

{% for todo in todos %}
<div class="card">
    <div class="card-body">
        <a href="{% url 'todo:view_todo' todo.pk %}">
            {% if todo.important %}<strong>{% endif %}{{ todo.title }}{% if todo.important %}</strong>{% endif %}
            {% if todo.memo %} -- {{ todo.memo }}{% endif %}
        </a>
    </div>
</div>

<br>
{% endfor %}

{% endblock content %}

todo/templates/todo/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="text-center">
        <br>
        <br>
        <br>
        <br>
        <br>

        <h1>Simply Your Todos. Woo!</h1>

        <p>
            Life is fun. But life is also busy. There's a million different things you could be doing. But what<br>matters
            is <a href="{% url 'authentication:login_user' %}">what</a> you do. We created <strong><em>Todo Woo</em></strong> to
            help you make sense of all of your<br>opportunities and live that life
            that matters most of you. You new organized life awaits.
        </p>

        <a role="button" class="btn btn-primary btn-lg" href="{% url 'authentication:register_user' %}">Start</a>
    </div>
</div>
{% endblock content %}

todo/templates/todo/view_todo.html
{% extends 'base.html' %}

{% block content %}

{{ todo.title }}

<form action="{% url 'todo:view_todo' todo.pk %}" method="POST">
    {{ form.as_p }}

    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-outline-success">Save</button>

</form>

<form action="{% url 'todo:task_accomplished' todo.pk %}" method="POST">
    <button type="submit" class="btn btn-outline-primary">Complete</button>
</form>

<form action="{% url 'todo:delete_todo' todo.pk %}" method="POST">
    <button type="submit" class="btn btn-outline-danger">Delete</button>
</form>

</div>


{% endblock %}